// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoGIzC0SVXsxQxm8qJkwZRRo8-fmJgn4A',
    appId: '1:19220273109:web:d25e5b37c55ec5afe7cf5c',
    messagingSenderId: '19220273109',
    projectId: 'macondo-vs',
    authDomain: 'macondo-vs.firebaseapp.com',
    storageBucket: 'macondo-vs.firebasestorage.app',
    measurementId: 'G-JF58NHSYH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv-_tcYhG8TEUIEnIcD_O6eIngWx1IIpA',
    appId: '1:19220273109:android:b4e3d3af1f3a3f5be7cf5c',
    messagingSenderId: '19220273109',
    projectId: 'macondo-vs',
    storageBucket: 'macondo-vs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH6UdJKhdugKwDU9ABNxfaMCg4iwrMHOk',
    appId: '1:19220273109:ios:ed1b2bb94d8c6acbe7cf5c',
    messagingSenderId: '19220273109',
    projectId: 'macondo-vs',
    storageBucket: 'macondo-vs.firebasestorage.app',
    iosBundleId: 'com.example.macondoVivoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH6UdJKhdugKwDU9ABNxfaMCg4iwrMHOk',
    appId: '1:19220273109:ios:ed1b2bb94d8c6acbe7cf5c',
    messagingSenderId: '19220273109',
    projectId: 'macondo-vs',
    storageBucket: 'macondo-vs.firebasestorage.app',
    iosBundleId: 'com.example.macondoVivoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoGIzC0SVXsxQxm8qJkwZRRo8-fmJgn4A',
    appId: '1:19220273109:web:85b78ce3a0502992e7cf5c',
    messagingSenderId: '19220273109',
    projectId: 'macondo-vs',
    authDomain: 'macondo-vs.firebaseapp.com',
    storageBucket: 'macondo-vs.firebasestorage.app',
    measurementId: 'G-7QHBJ3ER0E',
  );
}
